### PR TITLE
Modifying the schema

### PR DESCRIPTION
**Pull request by C4L86**

### CODE REVIEW

**Comment by C4L86** [comment]
We created our 'roles' table with a migration and attempted to add 'resources :roles' to config routes but encountered the following error:

/Users/changeme/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/administrate-0.1.4/lib/generators/administrate/dashboard/dashboard_generator.rb:107:in `const_get': uninitialized constant Role (NameError)

It started to create a 'roles' dashboard but it is blank and no model or controller was created.

**Comment by halfghaninne** [comment]
Did you run `rake db:migrate` after saving and closing the migration you wrote?

**Comment by C4L86** [comment]
we tried 'bundle exec db:migrate'

**Comment by C4L86** [comment]
correction: bundle exec rake db:migrate

**Pull request merged**
